name: Run Backend Tests

on: [push, pull_request] # Запуск тестов при пуше и PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Версия Go

      - name: Install dependencies
        run: go mod tidy
        working-directory: backend # Указываем папку с go.mod

      - name: Run tests
        run: go test ./...
        working-directory: backend
